INSERT INTO COURSE 
VALUES
(2,'back-end','The Science of Well-Being from Yale University '),
(3,'back-end','CS50’s Introduction to Computer Science from Harvard University '),
(4,'front-end','Learning How to Learn: Powerful mental tools to help you master tough subjects from University of California, San Diego '),
(5,'front-end','Programming for Everybody '),
(6,'back-end','English for Career Development from University of Pennsylvania '),
(7,'back-end','Introduction to Computer Science and Programming Using Python from Massachusetts Institute of Technology '),
(8,'front-end','COVID-19 Contact Tracing from Johns Hopkins University '),
(9,'front-end','IELTS Academic Test Preparation from University of Queensland '),
(10,'back-end','TOEFL® Test Preparation: The Insider’s Guide from ETS '),
(11,'back-end','Successful Negotiation: Essential Strategies and Skills from University of Michigan '),
(12,'front-end','First Step Korean from Yonsei University '),
(13,'front-end','Financial Markets from Yale University '),
(14,'back-end','Chinese for Beginners from Peking University '),
(15,'back-end','Neural Networks and Deep Learning from deeplearning.ai '),
(16,'front-end','Technical Support Fundamentals from Google '),
(17,'front-end','Algorithms, Part I from Princeton University '),
(18,'back-end','Analyzing and Visualizing Data with Excel from Microsoft '),
(19,'back-end','Introduction to Psychology from Yale University '),
(20,'front-end','Speak English Professionally: In Person, Online & On the Phone from Georgia Institute of Technology '),
(21,'front-end','Exploring English: Language and Culture from British Council '),
(22,'back-end','Introduction to Linux from Linux Foundation '),
(23,'back-end','AI For Everyone from deeplearning.ai '),
(24,'front-end','English Grammar and Style from University of Queensland '),
(25,'front-end','Basic English 1: Elementary from King’s College London '),
(26,'back-end','Entrepreneurship in Emerging Economies from Harvard University '),
(27,'back-end','Data Science: R Basics from Harvard University '),
(28,'front-end','The Data Scientist’s Toolbox from Johns Hopkins University '),
(29,'front-end','HTML, CSS, and Javascript for Web Developers from Johns Hopkins University '),
(30,'back-end','Excel Skills for Business: Essentials from Macquarie University '),
(31,'back-end','Stanford Introduction to Food and Health from Stanford University '),
(32,'front-end','Introduction to Data Science in Python from University of Michigan '),
(33,'front-end','Grammar and Punctuation from University of California, Irvine '),
(34,'back-end','Bitcoin and Cryptocurrency Technologies from Princeton University '),
(35,'back-end','English for the Workplace from British Council '),
(36,'front-end','Foundations: Data, Data, Everywhere from Google '),
(37,'front-end','Google Cloud Fundamentals: Core Infrastructure from Google '),
(38,'back-end','Fundamentals of Graphic Design from California Institute of the Arts '),
(39,'back-end','Buddhism and Modern Psychology from Princeton University '),
(40,'front-end','Introduction to Philosophy from University of Edinburgh '),
(41,'front-end','What is Data Science? from IBM '),
(42,'back-end','Marketing in a Digital World from University of Illinois at Urbana-Champaign '),
(43,'back-end','The Science of Happiness from University of California, Berkeley '),
(44,'front-end','Basic Spanish 1: Getting Started from Universitat Politècnica de València '),
(45,'front-end','Rhetoric: The Art of Persuasive Writing and Public Speaking from Harvard University '),
(46,'back-end','Contract Law: From Trust to Promise to Contract from Harvard University '),
(47,'back-end','The Architectural Imagination from Harvard University '),
(48,'front-end','Justice from Harvard University '),
(49,'front-end','Social Psychology from Wesleyan University '),
(50,'back-end','Crash Course on Python from Google'),
(51,'back-end','Fundamentals of Neuroscience, Part 1: The Electrical Properties of the Neuron from Harvard University '),
(52,'front-end','Programming for Everybody '),
(53,'front-end','Programming Foundations with JavaScript, HTML and CSS from Duke University '),
(54,'back-end','Finanzas personales from Universidad Nacional Autónoma de México'),
(55,'back-end','Python Basics for Data Science from IBM '),
(56,'front-end','Introduction to HTML5 from University of Michigan '),
(57,'front-end','Indigenous Canada from University of Alberta '),
(58,'back-end','Child Nutrition and Cooking from Stanford University '),
(59,'back-end','A Life of Happiness and Fulfillment from Indian School of Business '),
(60,'front-end','Introduction to Programming with MATLAB from Vanderbilt University '),
(61,'front-end','Algorithmic Toolbox from University of California, San Diego '),
(62,'back-end','Primeros Auxilios Psicológicos '),
(63,'back-end','Psychological First Aid from Johns Hopkins University '),
(64,'front-end','Introduction to Negotiation: A Strategic Playbook for Becoming a Principled and Persuasive Negotiator from Yale University '),
(65,'front-end','Work Smarter, Not Harder: Time Management for Personal & Professional Productivity from University of California, Irvine '),
(66,'back-end','Modern Art & Ideas from The Museum of Modern Art '),
(67,'back-end','Foundations of Project Management from Google '),
(68,'front-end','Introductory Human Physiology from Duke University '),
(69,'front-end','Introduction to Psychology from University of Toronto '),
(70,'back-end','Introduction to Project Management from University of Adelaide '),
(71,'back-end','Mindfulness for Wellbeing and Peak Performance from Monash University '),
(72,'front-end','Financial Engineering and Risk Management Part I from Columbia University '),
(73,'front-end','Basic English 2: Pre-Intermediate from King’s College London '),
(74,'back-end','Mindshift: Break Through Obstacles to Learning and Discover Your Hidden Potential from McMaster University '),
(75,'back-end','Contabilidad para no contadores from Universidad Nacional Autónoma de México'),
(76,'front-end','Academic and Business Writing from University of California, Berkeley '),
(77,'front-end','Étudier en France: French Intermediate course B1-B2 from École Polytechnique '),
(78,'back-end','Start Writing Fiction from The Open University '),
(79,'back-end','Introduction to Mathematical Thinking from Stanford University '),
(80,'front-end','HTML5 and CSS Fundamentals from World Wide Web Consortium '),
(81,'front-end','Initiating and Planning Projects from University of California, Irvine '),
(82,'back-end','Statistics and R from Harvard University '),
(83,'back-end','Game Theory from Stanford University '),
(84,'front-end','Excel: Fundamentos y herramientas from Universitat Politècnica de València '),
(85,'front-end','Design Thinking for Innovation from University of Virginia '),
(86,'back-end','SQL for Data Science from University of California, Davis '),
(87,'back-end','Competitive Strategy from Ludwig-Maximilians-Universität München '),
(88,'front-end','How to Write an Essay from University of California, Berkeley '),
(89,'front-end','English for Business and Entrepreneurship from University of Pennsylvania '),
(90,'back-end','A Beginner’s Guide to Writing in English for University Study from University of Reading '),
(91,'back-end','Machine Learning Foundations: A Case Study Approach from University of Washington '),
(92,'front-end','Cryptography I from Stanford University '),
(93,'front-end','Introduction to Java Programming: Starting to code in Java from Universidad Carlos iii de Madrid '),
(94,'back-end','Mechanical Ventilation for COVID-19 from Harvard University '),
(95,'back-end','Gestión de proyectos de desarrollo from IDB '),
(96,'front-end','Learn to Speak Korean 1 from Yonsei University '),
(97,'front-end','English Composition I from Duke University '),
(98,'back-end','Conversational English Skills | 生活英语听说 from Tsinghua University '),
(99,'back-end','Introduction to C++ from Microsoft '),
(100,'front-end','The Science of Everyday Thinking from University of Queensland '),
(101,'front-end','Foundations of User Experience '),
(102,'back-end','Build Your First Android App '),
(103,'back-end','Mastering Data Analysis in Excel from Duke University '),
(104,'front-end','Teaching English Online from Cambridge English Language Assessment '),
(105,'front-end','Introduction to Cyber Security from The Open University '),
(106,'back-end','Principles of Biochemistry from Harvard University '),
(107,'back-end','Aprendiendo a aprender: Poderosas herramientas mentales con las que podrás dominar temas difíciles '),
(108,'front-end','Using Python for Research from Harvard University '),
(109,'front-end','Introduction to Marketing from University of Pennsylvania '),
(110,'back-end','Python for Data Science from University of California, San Diego '),
(111,'back-end','Data Science Math Skills from Duke University '),
(112,'front-end','Python Basics from University of Michigan '),
(113,'front-end','Marketing Analytics from University of Virginia '),
(114,'back-end','Writing in the Sciences from Stanford University '),
(115,'back-end','Leaders of Learning from Harvard University '),
(116,'front-end','Science of Exercise from University of Colorado Boulder '),
(117,'front-end','Introduction to Java Programming – Part 1 from The Hong Kong University of Science and Technology '),
(118,'back-end','Think Again I: How to Understand Arguments from Duke University '),
(119,'back-end','Vital Signs: Understanding What the Body Is Telling Us from University of Pennsylvania '),
(120,'front-end','Introduction to Big Data from University of California, San Diego '),
(121,'front-end','Guitar for Beginners from Berklee College of Music '),
(122,'back-end','Introduction to TensorFlow for Artificial Intelligence, Machine Learning, and Deep Learning from deeplearning.ai '),
(123,'back-end','Artificial Intelligence '),
(124,'front-end','Introduction to the Internet of Things and Embedded Systems from University of California, Irvine '),
(125,'front-end','How to Succeed at: Interviews from The University of Sheffield '),
(126,'back-end','Positive Psychology from The University of North Carolina at Chapel Hill '),
(127,'back-end','Fundamentals of Music Theory from University of Edinburgh '),
(128,'front-end','Learn to Program: The Fundamentals from University of Toronto '),
(129,'front-end','Camino a la Excelencia en Gestión de Proyectos from Pontificia Universidad Católica de Chile'),
(130,'back-end','The Strategy of Content Marketing from University of California, Davis '),
(131,'back-end','Mathematics for Machine Learning: Linear Algebra from Imperial College London '),
(132,'front-end','Exploring English: Shakespeare from British Council '),
(133,'front-end','Understanding Language: Learning and Teaching from University of Southampton '),
(134,'back-end','Fundamentos de Excel para Negocios from Universidad Austral '),
(135,'back-end','How to Succeed at: Writing Applications from The University of Sheffield '),
(136,'front-end','Italian Language and Culture: Beginner '),
(137,'front-end','Medical Neuroscience from Duke University '),
(138,'back-end','Introduction to Dutch from University of Groningen '),
(139,'back-end','Aprender from Universidad Nacional Autónoma de México '),
(140,'front-end','Child Protection: Children’s Rights in Theory and Practice from Harvard University '),
(141,'front-end','An Introduction to Screenwriting from University of East Anglia '),
(142,'back-end','Supply Chain Fundamentals from Massachusetts Institute of Technology '),
(143,'back-end','Introduction to User Experience Design from Georgia Institute of Technology'),
(144,'front-end','Front-End Web UI Frameworks and Tools: Bootstrap 4 from The Hong Kong University of Science and Technology'),
(145,'front-end','Probability – The Science of Uncertainty and Data from Massachusetts Institute of Technology '),
(146,'front-end','Basic Statistics from University of Amsterdam '),
(147,'back-end','Introduction to Personal Branding from University of Virginia '),
(148,'back-end','AWS Fundamentals: Going Cloud-Native from Amazon Web Services '),
(149,'front-end','Algorithms, Part II from Princeton University '),
(150,'front-end','Learn to Program in Java from Microsoft '),
(151,'back-end','Brand Management: Aligning Business, Brand and Behaviour from University of London International Programmes '),
(152,'back-end','Programming Basics from Indian Institute of Technology Bombay '),
(153,'front-end','Querying Data with Transact-SQL from Microsoft '),
(154,'front-end','Introduction to Probability and Data with R from Duke University '),
(155,'front-end','Álgebra básica from Universidad Nacional Autónoma de México'),
(156,'back-end','Fundamentals of Project Planning and Management from University of Virginia '),
(157,'back-end','Google Cloud Big Data and Machine Learning Fundamentals from Google Cloud '),
(158,'front-end','Understanding Research Methods from University of London International Programmes '),
(159,'front-end','Robótica from Universidad Nacional Autónoma de México '),
(160,'back-end','A Hands-on Introduction to Engineering Simulations from Cornell University '),
(161,'back-end','Customer Analytics from University of Pennsylvania '),
(162,'front-end','Food as Medicine from Monash University '),
(163,'front-end','Code Yourself! An Introduction to Programming from University of Edinburgh '),
(164,'front-end','Introduction to Kubernetes from Linux Foundation'),
(165,'back-end','Viral Marketing and How to Craft Contagious Content from University of Pennsylvania '),
(166,'back-end','Becoming a Successful Leader '),
(167,'front-end','English in Early Childhood: Language Learning and Development from British Council '),
(168,'front-end','Cameras, Exposure, and Photography from Michigan State University '),
(169,'back-end','Nutrition and Health: Macronutrients and Overnutrition from Wageningen University '),
(170,'back-end','How Things Work: An Introduction to Physics from University of Virginia '),
(171,'front-end','Digital Skills: Digital Marketing from Accenture '),
(172,'front-end','Python Programming: A Concise Introduction from Wesleyan University '),
(173,'front-end','Understanding the Brain: The Neurobiology of Everyday Life from The University of Chicago '),
(174,'back-end','C++ For C Programmers, Part A from University of California, Santa Cruz '),
(175,'back-end','Cómo hacer una tesis from Universidad Nacional Autónoma de México '),
(176,'front-end','Introduction to Google SEO from University of California, Davis '),
(177,'front-end','Gestión Empresarial Exitosa para Pymes from Pontificia Universidad Católica de Chile'),
(178,'back-end','Creative Problem Solving from University of Minnesota '),
(179,'back-end','Introduction to Data Analysis Using Excel from Rice University '),
(180,'front-end','Statistical Thinking for Data Science and Analytics from Columbia University '),
(181,'front-end','Introduction to Classical Music from Yale University '),
(182,'front-end','Introduction to Engineering Mechanics from Georgia Institute of Technology '),
(183,'back-end','Inglés básico: conversacional y networking from Universidad Anáhuac '),
(184,'back-end','Introduction to Public Speaking from University of Washington '),
(185,'front-end','Begin Programming: Build Your First Mobile Game from University of Reading '),
(186,'front-end','Creative Writing: The Craft of Plot from Wesleyan University '),
(187,'back-end','Computing in Python I: Fundamentals and Procedural Programming from Georgia Institute of Technology '),
(188,'back-end','Buddhism Through Its Scriptures from Harvard University '),
(189,'front-end','De-Mystifying Mindfulness from Leiden University '),
(190,'front-end','Introduction to Marketing from The University of British Columbia '),
(191,'front-end','Tricky American English Pronunciation from University of California, Irvine '),
(192,'back-end','Creative Thinking: Techniques and Tools for Success from Imperial College London '),
(193,'back-end','How to Learn Online'),
(194,'front-end','Logical and Critical Thinking from University Of Auckland '),
(195,'front-end','Functional Programming Principles in Scala from École Polytechnique Fédérale de Lausanne '),
(196,'back-end','Greek and Roman Mythology from University of Pennsylvania '),
(197,'back-end','How to Write a Resume '),
(198,'front-end','Nutrición y obesidad: control de sobrepeso from Universidad Nacional Autónoma de México '),
(199,'front-end','Forensic Psychology: Witness Investigation from The Open University '),
(200,'front-end','Positive Psychiatry and Mental Health from The University of Sydney '),
(201,'back-end','Management of Fashion and Luxury Companies from Università Bocconi '),
(202,'back-end','An Introduction to Interactive Programming in Python '),
(203,'front-end','Introducción a la programación en Python I: Aprendiendo a programar con Python from Pontificia Universidad Católica de Chile '),
(204,'front-end','Cybersecurity Fundamentals from Rochester Institute of Technology '),
(205,'back-end','Java for Android from Vanderbilt University '),
(206,'back-end','Introducción a Data Science: Programación Estadística con R from Universidad Nacional Autónoma de México '),
(207,'front-end','Dog Emotion and Cognition from Duke University '),
(208,'front-end','Divide and Conquer, Sorting and Searching, and Randomized Algorithms from Stanford University '),
(209,'front-end','Ser más creativos from Universidad Nacional Autónoma de México '),
(210,'back-end','Introduction to Cybersecurity Tools & Cyber Attacks from IBM '),
(211,'back-end','Astronomy: Exploring Time and Space from University of Arizona '),
(212,'front-end','Introduction to Web Development from University of California, Davis '),
(213,'front-end','Getting Started with AWS Machine Learning from Amazon Web Services '),
(214,'back-end','Introduction to Logic from Stanford University '),
(215,'back-end','English for Journalism from University of Pennsylvania '),
(216,'front-end','A Crash Course in Data Science from Johns Hopkins University '),
(217,'front-end','Influencing People from University of Michigan '),
(218,'front-end','Introdução à Ciência da Computação com Python Parte 1 from Universidade de São Paulo '),
(219,'back-end','Introduction to Biology – The Secret of Life from Massachusetts Institute of Technology '),
(220,'back-end','Computer Architecture from Princeton University '),
(221,'front-end','Introduction to Electronics from Georgia Institute of Technology '),
(222,'front-end','How To Create a Website in a Weekend! '),
(223,'back-end','Aprendendo a aprender: ferramentas mentais poderosas para ajudá-lo a dominar assuntos difíceis '),
(224,'back-end','Mind Control: Managing Your Mental Health During COVID-19 from University of Toronto '),
(225,'front-end','Model Thinking from University of Michigan '),
(226,'front-end','Moral Foundations of Politics from Yale University '),
(227,'front-end','Responsive Website Basics: Code with HTML, CSS, and JavaScript from University of London International Programmes '),
(228,'back-end','Epidemiology: The Basic Science of Public Health from The University of North Carolina at Chapel Hill '),
(229,'back-end','Competencias digitales. Herramientas de ofimática '),
(230,'front-end','Spanish Vocabulary: Meeting People from University of California, Davis '),
(231,'front-end','Introduction to the Biology of Cancer from Johns Hopkins University '),
(232,'back-end','The Modern World, Part One: Global History from 1760 to 1910 from University of Virginia '),
(233,'back-end','Supply Chain Logistics from Rutgers University '),
(234,'front-end','Introduction to Deep Learning from Higher School of Economics '),
(235,'front-end','Starting a Business 1: Vision and Opportunity from University of Leeds '),
(236,'front-end','Cybersecurity and Its Ten Domains from University System of Georgia '),
(237,'back-end','Bitcoin and Cryptocurrencies from University of California, Berkeley'),
(238,'back-end','Business English: Networking from University of Washington '),
(239,'front-end','Management and Leadership: Growing as a Manager from The Open University '),
(240,'front-end','Human Anatomy: Musculoskeletal Cases from Harvard University '),
(241,'back-end','Programming Fundamentals from Duke University'),
(242,'back-end','The Addicted Brain from Emory University '),
(243,'front-end','Communication and Interpersonal Skills at Work from University of Leeds '),
(244,'front-end','English for Academic Study from Coventry University '),
(245,'front-end','Database Management Essentials from University of Colorado System '),
(246,'back-end','Blockchain Basics from University at Buffalo '),
(247,'back-end','Perfect Tenses and Modals from University of California, Irvine '),
(248,'front-end','Introduction to Social Media Marketing from Facebook'),
(249,'front-end','Preparing to Manage Human Resources from University of Minnesota '),
(250,'back-end','Miracles of Human Language: An Introduction to Linguistics from Leiden University ')
